# Generated by Django 2.2.1 on 2019-05-09 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ejemplo',
            fields=[
                ('ejemplo', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, null=True)),
                ('release_date', models.DateField()),
                ('list', models.CharField(choices=[('V1', 'v1'), ('V2', 'v2'), ('V3', 'v3'), ('V4', 'v4')], max_length=10)),
            ],
            options={
                'db_table': 'ejemplo',
            },
        ),
    ]
