# Generated by Django 2.2.1 on 2019-05-09 15:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ejemplo', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ejemplo',
            old_name='ejemplo',
            new_name='ejemplo_id',
        ),
    ]
